// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package client

import (
	"time"
)

// Defines values for CharacterPassivesBanditChoice.
const (
	Alira   CharacterPassivesBanditChoice = "Alira"
	Eramir  CharacterPassivesBanditChoice = "Eramir"
	Kraityn CharacterPassivesBanditChoice = "Kraityn"
	Oak     CharacterPassivesBanditChoice = "Oak"
)

// Valid indicates whether the value is a known member of the CharacterPassivesBanditChoice enum.
func (e CharacterPassivesBanditChoice) Valid() bool {
	switch e {
	case Alira:
		return true
	case Eramir:
		return true
	case Kraityn:
		return true
	case Oak:
		return true
	default:
		return false
	}
}

// Defines values for CharacterPassivesPantheonMajor.
const (
	Arakaali     CharacterPassivesPantheonMajor = "Arakaali"
	Lunaris      CharacterPassivesPantheonMajor = "Lunaris"
	Solaris      CharacterPassivesPantheonMajor = "Solaris"
	TheBrineKing CharacterPassivesPantheonMajor = "TheBrineKing"
)

// Valid indicates whether the value is a known member of the CharacterPassivesPantheonMajor enum.
func (e CharacterPassivesPantheonMajor) Valid() bool {
	switch e {
	case Arakaali:
		return true
	case Lunaris:
		return true
	case Solaris:
		return true
	case TheBrineKing:
		return true
	default:
		return false
	}
}

// Defines values for CharacterPassivesPantheonMinor.
const (
	Abberath CharacterPassivesPantheonMinor = "Abberath"
	Garukhan CharacterPassivesPantheonMinor = "Garukhan"
	Gruthkul CharacterPassivesPantheonMinor = "Gruthkul"
	Ralakesh CharacterPassivesPantheonMinor = "Ralakesh"
	Ryslatha CharacterPassivesPantheonMinor = "Ryslatha"
	Shakari  CharacterPassivesPantheonMinor = "Shakari"
	Tukohama CharacterPassivesPantheonMinor = "Tukohama"
	Yugul    CharacterPassivesPantheonMinor = "Yugul"
)

// Valid indicates whether the value is a known member of the CharacterPassivesPantheonMinor enum.
func (e CharacterPassivesPantheonMinor) Valid() bool {
	switch e {
	case Abberath:
		return true
	case Garukhan:
		return true
	case Gruthkul:
		return true
	case Ralakesh:
		return true
	case Ryslatha:
		return true
	case Shakari:
		return true
	case Tukohama:
		return true
	case Yugul:
		return true
	default:
		return false
	}
}

// Defines values for CreateItemFilterRequestType.
const (
	CreateItemFilterRequestTypeNormal   CreateItemFilterRequestType = "Normal"
	CreateItemFilterRequestTypeRuthless CreateItemFilterRequestType = "Ruthless"
)

// Valid indicates whether the value is a known member of the CreateItemFilterRequestType enum.
func (e CreateItemFilterRequestType) Valid() bool {
	switch e {
	case CreateItemFilterRequestTypeNormal:
		return true
	case CreateItemFilterRequestTypeRuthless:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	N200 ErrorCode = 200
	N202 ErrorCode = 202
	N400 ErrorCode = 400
	N404 ErrorCode = 404
	N429 ErrorCode = 429
	N500 ErrorCode = 500
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case N200:
		return true
	case N202:
		return true
	case N400:
		return true
	case N404:
		return true
	case N429:
		return true
	case N500:
		return true
	default:
		return false
	}
}

// Defines values for FactionId.
const (
	Faction1 FactionId = "Faction1"
	Faction2 FactionId = "Faction2"
	Faction3 FactionId = "Faction3"
	Faction4 FactionId = "Faction4"
)

// Valid indicates whether the value is a known member of the FactionId enum.
func (e FactionId) Valid() bool {
	switch e {
	case Faction1:
		return true
	case Faction2:
		return true
	case Faction3:
		return true
	case Faction4:
		return true
	default:
		return false
	}
}

// Defines values for ItemColour.
const (
	ItemColourD ItemColour = "D"
	ItemColourG ItemColour = "G"
	ItemColourI ItemColour = "I"
	ItemColourS ItemColour = "S"
)

// Valid indicates whether the value is a known member of the ItemColour enum.
func (e ItemColour) Valid() bool {
	switch e {
	case ItemColourD:
		return true
	case ItemColourG:
		return true
	case ItemColourI:
		return true
	case ItemColourS:
		return true
	default:
		return false
	}
}

// Defines values for ItemRarity.
const (
	ItemRarityMagic  ItemRarity = "Magic"
	ItemRarityNormal ItemRarity = "Normal"
	ItemRarityRare   ItemRarity = "Rare"
	ItemRarityUnique ItemRarity = "Unique"
)

// Valid indicates whether the value is a known member of the ItemRarity enum.
func (e ItemRarity) Valid() bool {
	switch e {
	case ItemRarityMagic:
		return true
	case ItemRarityNormal:
		return true
	case ItemRarityRare:
		return true
	case ItemRarityUnique:
		return true
	default:
		return false
	}
}

// Defines values for ItemFilterType.
const (
	ItemFilterTypeNormal   ItemFilterType = "Normal"
	ItemFilterTypeRuthless ItemFilterType = "Ruthless"
)

// Valid indicates whether the value is a known member of the ItemFilterType enum.
func (e ItemFilterType) Valid() bool {
	switch e {
	case ItemFilterTypeNormal:
		return true
	case ItemFilterTypeRuthless:
		return true
	default:
		return false
	}
}

// Defines values for ItemSocketAttr.
const (
	ItemSocketAttrA  ItemSocketAttr = "A"
	ItemSocketAttrD  ItemSocketAttr = "D"
	ItemSocketAttrDV ItemSocketAttr = "DV"
	ItemSocketAttrG  ItemSocketAttr = "G"
	ItemSocketAttrI  ItemSocketAttr = "I"
	ItemSocketAttrS  ItemSocketAttr = "S"
)

// Valid indicates whether the value is a known member of the ItemSocketAttr enum.
func (e ItemSocketAttr) Valid() bool {
	switch e {
	case ItemSocketAttrA:
		return true
	case ItemSocketAttrD:
		return true
	case ItemSocketAttrDV:
		return true
	case ItemSocketAttrG:
		return true
	case ItemSocketAttrI:
		return true
	case ItemSocketAttrS:
		return true
	default:
		return false
	}
}

// Defines values for ItemSocketItem.
const (
	ItemSocketItemActivegem      ItemSocketItem = "activegem"
	ItemSocketItemEmerald        ItemSocketItem = "emerald"
	ItemSocketItemPrimaltalisman ItemSocketItem = "primaltalisman"
	ItemSocketItemRuby           ItemSocketItem = "ruby"
	ItemSocketItemRune           ItemSocketItem = "rune"
	ItemSocketItemSacredtalisman ItemSocketItem = "sacredtalisman"
	ItemSocketItemSapphire       ItemSocketItem = "sapphire"
	ItemSocketItemSoulcore       ItemSocketItem = "soulcore"
	ItemSocketItemSupportgem     ItemSocketItem = "supportgem"
	ItemSocketItemVividtalisman  ItemSocketItem = "vividtalisman"
	ItemSocketItemWildtalisman   ItemSocketItem = "wildtalisman"
)

// Valid indicates whether the value is a known member of the ItemSocketItem enum.
func (e ItemSocketItem) Valid() bool {
	switch e {
	case ItemSocketItemActivegem:
		return true
	case ItemSocketItemEmerald:
		return true
	case ItemSocketItemPrimaltalisman:
		return true
	case ItemSocketItemRuby:
		return true
	case ItemSocketItemRune:
		return true
	case ItemSocketItemSacredtalisman:
		return true
	case ItemSocketItemSapphire:
		return true
	case ItemSocketItemSoulcore:
		return true
	case ItemSocketItemSupportgem:
		return true
	case ItemSocketItemVividtalisman:
		return true
	case ItemSocketItemWildtalisman:
		return true
	default:
		return false
	}
}

// Defines values for ItemSocketSColour.
const (
	ItemSocketSColourA  ItemSocketSColour = "A"
	ItemSocketSColourB  ItemSocketSColour = "B"
	ItemSocketSColourDV ItemSocketSColour = "DV"
	ItemSocketSColourG  ItemSocketSColour = "G"
	ItemSocketSColourR  ItemSocketSColour = "R"
	ItemSocketSColourW  ItemSocketSColour = "W"
)

// Valid indicates whether the value is a known member of the ItemSocketSColour enum.
func (e ItemSocketSColour) Valid() bool {
	switch e {
	case ItemSocketSColourA:
		return true
	case ItemSocketSColourB:
		return true
	case ItemSocketSColourDV:
		return true
	case ItemSocketSColourG:
		return true
	case ItemSocketSColourR:
		return true
	case ItemSocketSColourW:
		return true
	default:
		return false
	}
}

// Defines values for ItemSocketType.
const (
	ItemSocketTypeGem   ItemSocketType = "gem"
	ItemSocketTypeJewel ItemSocketType = "jewel"
	ItemSocketTypeRune  ItemSocketType = "rune"
)

// Valid indicates whether the value is a known member of the ItemSocketType enum.
func (e ItemSocketType) Valid() bool {
	switch e {
	case ItemSocketTypeGem:
		return true
	case ItemSocketTypeJewel:
		return true
	case ItemSocketTypeRune:
		return true
	default:
		return false
	}
}

// Defines values for LeagueRuleId.
const (
	Hardcore  LeagueRuleId = "Hardcore"
	NoParties LeagueRuleId = "NoParties"
)

// Valid indicates whether the value is a known member of the LeagueRuleId enum.
func (e LeagueRuleId) Valid() bool {
	switch e {
	case Hardcore:
		return true
	case NoParties:
		return true
	default:
		return false
	}
}

// Defines values for MarketMarketId.
const (
	MetadataItemsCurrencyCurrencyRerollRareMetadataItemsCurrencyCurrencyModValues MarketMarketId = "Metadata/Items/Currency/CurrencyRerollRare|Metadata/Items/Currency/CurrencyModValues"
)

// Valid indicates whether the value is a known member of the MarketMarketId enum.
func (e MarketMarketId) Valid() bool {
	switch e {
	case MetadataItemsCurrencyCurrencyRerollRareMetadataItemsCurrencyCurrencyModValues:
		return true
	default:
		return false
	}
}

// Defines values for PvPMatchStyle.
const (
	Arena PvPMatchStyle = "Arena"
	Blitz PvPMatchStyle = "Blitz"
	Swiss PvPMatchStyle = "Swiss"
)

// Valid indicates whether the value is a known member of the PvPMatchStyle enum.
func (e PvPMatchStyle) Valid() bool {
	switch e {
	case Arena:
		return true
	case Blitz:
		return true
	case Swiss:
		return true
	default:
		return false
	}
}

// Defines values for Realm.
const (
	Pc   Realm = "pc"
	Poe2 Realm = "poe2"
	Sony Realm = "sony"
	Xbox Realm = "xbox"
)

// Valid indicates whether the value is a known member of the Realm enum.
func (e Realm) Valid() bool {
	switch e {
	case Pc:
		return true
	case Poe2:
		return true
	case Sony:
		return true
	case Xbox:
		return true
	default:
		return false
	}
}

// Defines values for UpdateItemFilterRequestType.
const (
	UpdateItemFilterRequestTypeNormal   UpdateItemFilterRequestType = "Normal"
	UpdateItemFilterRequestTypeRuthless UpdateItemFilterRequestType = "Ruthless"
)

// Valid indicates whether the value is a known member of the UpdateItemFilterRequestType enum.
func (e UpdateItemFilterRequestType) Valid() bool {
	switch e {
	case UpdateItemFilterRequestTypeNormal:
		return true
	case UpdateItemFilterRequestTypeRuthless:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	Challenges *AccountChallenges `json:"challenges,omitempty"`
	Guild      *Guild             `json:"guild,omitempty"`
	Name       string             `binding:"required" json:"name"`

	// Realm pc, xbox, or sony
	Realm  *Realm         `json:"realm,omitempty"`
	Twitch *AccountTwitch `json:"twitch,omitempty"`
}

// AccountChallenges defines model for AccountChallenges.
type AccountChallenges struct {
	Completed int `binding:"required" json:"completed"`
	Max       int `binding:"required" json:"max"`

	// Set the challenge set
	Set string `binding:"required" json:"set"`
}

// AccountTwitch defines model for AccountTwitch.
type AccountTwitch struct {
	Name   string  `binding:"required" json:"name"`
	Stream *Stream `json:"stream,omitempty"`
}

// Character defines model for Character.
type Character struct {
	Class string `binding:"required" json:"class"`

	// Current always true if present
	Current *bool `json:"current,omitempty"`

	// Deleted always true if present
	Deleted    *bool   `json:"deleted,omitempty"`
	Equipment  *[]Item `json:"equipment,omitempty"`
	Experience int     `binding:"required" json:"experience"`

	// Expired always true if present
	Expired *bool `json:"expired,omitempty"`

	// Guardian PoE1 only
	Guardian *[]Item `json:"guardian,omitempty"`

	// Id a unique 64 digit hexadecimal string
	Id string `binding:"required" json:"id"`

	// Inventory PoE1 only
	Inventory *[]Item            `json:"inventory,omitempty"`
	Jewels    *[]Item            `json:"jewels,omitempty"`
	League    *string            `json:"league,omitempty"`
	Level     int                `binding:"required" json:"level"`
	Metadata  *CharacterMetadata `json:"metadata,omitempty"`
	Name      string             `binding:"required" json:"name"`
	Passives  *CharacterPassives `json:"passives,omitempty"`

	// Realm pc, xbox, or sony
	Realm Realm `binding:"required" json:"realm"`

	// Rucksack PoE1 only
	Rucksack *[]Item `json:"rucksack,omitempty"`

	// Ruthless PoE1 only; always true if present
	Ruthless *bool `json:"ruthless,omitempty"`

	// Skills PoE2 only
	Skills *[]Item `json:"skills,omitempty"`
}

// CharacterMetadata defines model for CharacterMetadata.
type CharacterMetadata struct {
	// Version game version for the character's realm
	Version *string `json:"version,omitempty"`
}

// CharacterPassives defines model for CharacterPassives.
type CharacterPassives struct {
	// AlternateAscendancy PoE1 only; Bloodline class name
	AlternateAscendancy *string `json:"alternate_ascendancy,omitempty"`

	// BanditChoice PoE1 only; one of Kraityn, Alira, Oak, or Eramir
	BanditChoice *CharacterPassivesBanditChoice `json:"bandit_choice,omitempty"`
	Hashes       []int                          `binding:"required" json:"hashes"`

	// HashesEx PoE1 only
	HashesEx []int `binding:"required" json:"hashes_ex"`

	// JewelData the key is the string value of the x property of an item from the jewels array in this request
	JewelData map[string]ItemJewelData `binding:"required" json:"jewel_data"`

	// MasteryEffects PoE1 only; the key is the string value of the mastery node skill hash and the value is the selected effect hash
	MasteryEffects map[string]int `binding:"required" json:"mastery_effects"`

	// PantheonMajor PoE1 only; one of TheBrineKing, Arakaali, Solaris, or Lunaris
	PantheonMajor *CharacterPassivesPantheonMajor `json:"pantheon_major,omitempty"`

	// PantheonMinor PoE1 only; one of Abberath, Gruthkul, Yugul, Shakari, Tukohama, Ralakesh, Garukhan, or Ryslatha
	PantheonMinor *CharacterPassivesPantheonMinor `json:"pantheon_minor,omitempty"`

	// QuestStats PoE2 only; passives granted via quests
	QuestStats *[]string `json:"quest_stats,omitempty"`

	// SkillOverrides the key is the string value of the node identifier being replaced
	SkillOverrides map[string]PassiveNode `binding:"required" json:"skill_overrides"`

	// Specialisations PoE2 only; the keys are set1, set2, and set3
	Specialisations map[string][]int `binding:"required" json:"specialisations"`
}

// CharacterPassivesBanditChoice PoE1 only; one of Kraityn, Alira, Oak, or Eramir
type CharacterPassivesBanditChoice string

// CharacterPassivesPantheonMajor PoE1 only; one of TheBrineKing, Arakaali, Solaris, or Lunaris
type CharacterPassivesPantheonMajor string

// CharacterPassivesPantheonMinor PoE1 only; one of Abberath, Gruthkul, Yugul, Shakari, Tukohama, Ralakesh, Garukhan, or Ryslatha
type CharacterPassivesPantheonMinor string

// CreateItemFilterRequest defines model for CreateItemFilterRequest.
type CreateItemFilterRequest struct {
	Description *string `json:"description,omitempty"`
	Filter      string  `binding:"required" json:"filter"`
	FilterName  string  `binding:"required" json:"filter_name"`

	// Public defaults to false
	Public *bool `json:"public,omitempty"`

	// Realm pc, xbox, sony, or poe2
	Realm Realm `binding:"required" json:"realm"`

	// Type either Normal or Ruthless
	Type    *CreateItemFilterRequestType `json:"type,omitempty"`
	Version *string                      `json:"version,omitempty"`
}

// CreateItemFilterRequestType either Normal or Ruthless
type CreateItemFilterRequestType string

// CreateItemFilterResponse defines model for CreateItemFilterResponse.
type CreateItemFilterResponse struct {
	Filter ItemFilter `binding:"required" json:"filter"`
}

// CrucibleNode defines model for CrucibleNode.
type CrucibleNode struct {
	// Allocated always true if present
	Allocated *bool   `json:"allocated,omitempty"`
	Icon      *string `json:"icon,omitempty"`

	// In node identifiers of nodes connected to this one
	In []string `binding:"required" json:"in"`

	// IsNotable always true if present
	IsNotable *bool `json:"isNotable,omitempty"`

	// IsReward always true if present
	IsReward *bool `json:"isReward,omitempty"`

	// Orbit the column this node occupies
	Orbit *int `json:"orbit,omitempty"`

	// OrbitIndex the node's position within the column
	OrbitIndex *int `json:"orbitIndex,omitempty"`

	// Out node identifiers of nodes this one connects to
	Out          []string  `binding:"required" json:"out"`
	ReminderText *[]string `json:"reminderText,omitempty"`

	// Skill mod hash
	Skill *int `json:"skill,omitempty"`

	// Stats stat descriptions
	Stats *[]string `json:"stats,omitempty"`

	// Tier mod tier
	Tier *int `json:"tier,omitempty"`
}

// Depth defines model for Depth.
type Depth struct {
	Default *int `json:"default,omitempty"`
	Solo    *int `json:"solo,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    *ErrorCode `json:"code,omitempty"`
	Message *string    `json:"message,omitempty"`
}

// ErrorCode defines model for Error.Code.
type ErrorCode int

// EventLadderEntry defines model for EventLadderEntry.
type EventLadderEntry struct {
	Ineligible    *bool                         `json:"ineligible,omitempty"`
	PrivateLeague EventLadderEntryPrivateLeague `binding:"required" json:"private_league"`
	Rank          int                           `binding:"required" json:"rank"`

	// Time time taken to complete the league objective in seconds
	Time *int `json:"time,omitempty"`
}

// EventLadderEntryPrivateLeague defines model for EventLadderEntryPrivateLeague.
type EventLadderEntryPrivateLeague struct {
	Name string `binding:"required" json:"name"`

	// Url a url link to a Path of Exile Private League
	Url string `binding:"required" json:"url"`
}

// Faction defines model for Faction.
type Faction struct {
	// Id Faction1, Faction2, Faction3, or Faction4
	Id   FactionId `binding:"required" json:"id"`
	Name string    `binding:"required" json:"name"`
}

// FactionId Faction1, Faction2, Faction3, or Faction4
type FactionId string

// GemPage defines model for GemPage.
type GemPage struct {
	Description *string         `json:"description,omitempty"`
	Properties  *[]ItemProperty `json:"properties,omitempty"`
	SkillName   *string         `json:"skillName,omitempty"`
	Stats       *[]string       `json:"stats,omitempty"`
}

// GemTab defines model for GemTab.
type GemTab struct {
	Name  *string   `json:"name,omitempty"`
	Pages []GemPage `binding:"required" json:"pages"`
}

// GetCharacterResponse defines model for GetCharacterResponse.
type GetCharacterResponse struct {
	Character *Character `json:"character,omitempty"`
}

// GetExchangeMarketsResponse defines model for GetExchangeMarketsResponse.
type GetExchangeMarketsResponse struct {
	Markets []Market `binding:"required" json:"markets"`

	// NextChangeId unix timestamp truncated to the hour
	NextChangeId int `binding:"required" json:"next_change_id"`
}

// GetItemFiltersResponse defines model for GetItemFiltersResponse.
type GetItemFiltersResponse struct {
	Filters []ItemFilter `binding:"required" json:"filters"`
}

// GetLeagueAccountResponse defines model for GetLeagueAccountResponse.
type GetLeagueAccountResponse struct {
	LeagueAccount LeagueAccount `binding:"required" json:"league_account"`
}

// GetLeagueEventLadderResponse defines model for GetLeagueEventLadderResponse.
type GetLeagueEventLadderResponse struct {
	Ladder Ladder2 `binding:"required" json:"ladder"`
	League League  `binding:"required" json:"league"`
}

// GetLeagueLadderResponse defines model for GetLeagueLadderResponse.
type GetLeagueLadderResponse struct {
	Ladder Ladder `binding:"required" json:"ladder"`
	League League `binding:"required" json:"league"`
}

// GetLeagueResponse defines model for GetLeagueResponse.
type GetLeagueResponse struct {
	League *League `json:"league,omitempty"`
}

// GetProfileResponse defines model for GetProfileResponse.
type GetProfileResponse struct {
	Locale *string `json:"locale,omitempty"`
	Name   string  `binding:"required" json:"name"`

	// Twitch present if the account is Twitch-linked
	Twitch *Twitch `json:"twitch,omitempty"`

	// Uuid UUIDv4 in canonical format
	Uuid string `binding:"required" json:"uuid"`
}

// GetPublicStashesResponse defines model for GetPublicStashesResponse.
type GetPublicStashesResponse struct {
	// NextChangeId pagination code
	NextChangeId string              `binding:"required" json:"next_change_id"`
	Stashes      []PublicStashChange `binding:"required" json:"stashes"`
}

// GetPvpMatchLadderResponse defines model for GetPvpMatchLadderResponse.
type GetPvpMatchLadderResponse struct {
	Ladder Ladder3  `binding:"required" json:"ladder"`
	Match  PvPMatch `binding:"required" json:"match"`
}

// GetPvpMatchResponse defines model for GetPvpMatchResponse.
type GetPvpMatchResponse struct {
	Match *PvPMatch `json:"match,omitempty"`
}

// GetStashResponse defines model for GetStashResponse.
type GetStashResponse struct {
	Stash *StashTab `json:"stash,omitempty"`
}

// Guild defines model for Guild.
type Guild struct {
	Id   int    `binding:"required" json:"id"`
	Name string `binding:"required" json:"name"`
	Tag  string `binding:"required" json:"tag"`
}

// Item defines model for Item.
type Item struct {
	// AbyssJewel always true if present
	AbyssJewel           *bool           `json:"abyssJewel,omitempty"`
	AdditionalProperties *[]ItemProperty `json:"additionalProperties,omitempty"`
	ArtFilename          *string         `json:"artFilename,omitempty"`
	BaseType             string          `binding:"required" json:"baseType"`

	// BondedMods PoE2 only
	BondedMods *[]string `json:"bondedMods,omitempty"`

	// BuiltInSupport PoE1 only; Supported by level 1 x
	BuiltInSupport *string `json:"builtInSupport,omitempty"`

	// CisRaceReward always true if present
	CisRaceReward *bool `json:"cisRaceReward,omitempty"`

	// Colour PoE1 only; S, D, I, or G
	Colour *ItemColour `json:"colour,omitempty"`

	// Corrupted always true if present
	Corrupted    *bool         `json:"corrupted,omitempty"`
	CosmeticMods *[]string     `json:"cosmeticMods,omitempty"`
	Crucible     *ItemCrucible `json:"crucible,omitempty"`

	// CrucibleMods only allocated mods are included
	CrucibleMods *[]string `json:"crucibleMods,omitempty"`

	// Delve always true if present
	Delve     *bool   `json:"delve,omitempty"`
	DescrText *string `json:"descrText,omitempty"`

	// Desecrated PoE2 only; always true if present
	Desecrated *bool `json:"desecrated,omitempty"`

	// DoubleCorrupted PoE2 only; always true if present
	DoubleCorrupted *bool `json:"doubleCorrupted,omitempty"`

	// Duplicated always true if present
	Duplicated *bool `json:"duplicated,omitempty"`

	// Elder always true if present
	Elder        *bool           `json:"elder,omitempty"`
	EnchantMods  *[]string       `json:"enchantMods,omitempty"`
	Enshrouded   *ItemEnshrouded `json:"enshrouded,omitempty"`
	ExplicitMods *[]ItemMod      `json:"explicitMods,omitempty"`

	// Extended only present in the Public Stash API
	Extended    *ItemExtended `json:"extended,omitempty"`
	FlavourText *[]string     `json:"flavourText,omitempty"`

	// FlavourTextNote user-generated text
	FlavourTextNote *string `json:"flavourTextNote,omitempty"`
	FoilVariation   *int    `json:"foilVariation,omitempty"`

	// Foreseeing always true if present
	Foreseeing *bool `json:"foreseeing,omitempty"`

	// ForumNote user-generated text
	ForumNote *string `json:"forum_note,omitempty"`

	// Fractured always true if present
	Fractured *bool `json:"fractured,omitempty"`

	// FrameType deprecated; use frameTypeId
	FrameType   *int   `json:"frameType,omitempty"`
	FrameTypeId string `binding:"required" json:"frameTypeId"`

	// GemBackground PoE2 only
	GemBackground *string `json:"gemBackground,omitempty"`

	// GemSkill PoE2 only
	GemSkill *string `json:"gemSkill,omitempty"`

	// GemSockets PoE2 only; string is always W
	GemSockets *[]string `json:"gemSockets,omitempty"`

	// GemTabs PoE2 only
	GemTabs *[]GemTab `json:"gemTabs,omitempty"`

	// GrantedSkills PoE2 only
	GrantedSkills *[]ItemProperty `json:"grantedSkills,omitempty"`
	H             int             `binding:"required" json:"h"`
	Hybrid        *ItemHybrid     `json:"hybrid,omitempty"`
	Icon          string          `binding:"required" json:"icon"`

	// IconStackLevel describes the level of a stack of items
	IconStackLevel *string `json:"iconStackLevel,omitempty"`

	// IconTierText usually roman numerals
	IconTierText *string `json:"iconTierText,omitempty"`

	// Id a unique 64 digit hexadecimal string
	Id            *string                 `json:"id,omitempty"`
	Identified    bool                    `binding:"required" json:"identified"`
	Ilvl          int                     `binding:"required" json:"ilvl"`
	ImplicitMods  *[]ItemMod              `json:"implicitMods,omitempty"`
	IncubatedItem *ItemIncubatedItem      `json:"incubatedItem,omitempty"`
	Influences    *map[string]interface{} `json:"influences,omitempty"`
	InventoryId   *string                 `json:"inventoryId,omitempty"`

	// IsRelic always true if present
	IsRelic *bool `json:"isRelic,omitempty"`

	// ItemLevel used for items that always display their item level
	ItemLevel *int    `json:"itemLevel,omitempty"`
	League    *string `json:"league,omitempty"`

	// LockedToAccount always true if present
	LockedToAccount *bool `json:"lockedToAccount,omitempty"`

	// LockedToCharacter always true if present
	LockedToCharacter *bool             `json:"lockedToCharacter,omitempty"`
	LogbookMods       *[]ItemLogbookMod `json:"logbookMods,omitempty"`
	MaxStackSize      *int              `json:"maxStackSize,omitempty"`

	// MemoryItem always true if present
	MemoryItem      *bool                 `json:"memoryItem,omitempty"`
	MercenarySkills *[]ItemMercenarySkill `json:"mercenarySkills,omitempty"`

	// MonsterLevel PoE1 only; used for items that always display their monster level
	MonsterLevel *int `json:"monsterLevel,omitempty"`

	// Mutated PoE1: true on Foulborn Uniques, PoE2: true on all Vaal Uniques
	Mutated               *bool           `json:"mutated,omitempty"`
	Name                  string          `binding:"required" json:"name"`
	NextLevelRequirements *[]ItemProperty `json:"nextLevelRequirements,omitempty"`
	NotableProperties     *[]ItemProperty `json:"notableProperties,omitempty"`

	// Note user-generated text
	Note         *string         `json:"note,omitempty"`
	Properties   *[]ItemProperty `json:"properties,omitempty"`
	ProphecyText *string         `json:"prophecyText,omitempty"`

	// Rarity Normal, Magic, Rare, or Unique
	Rarity *ItemRarity `json:"rarity,omitempty"`

	// Realm always poe2 if present
	Realm *Realm `json:"realm,omitempty"`

	// Replica always true if present
	Replica      *bool           `json:"replica,omitempty"`
	Requirements *[]ItemProperty `json:"requirements,omitempty"`
	Rewards      *[]ItemReward   `json:"rewards,omitempty"`

	// RuneMods PoE2 only
	RuneMods *[]string `json:"runeMods,omitempty"`

	// Ruthless always true if present
	Ruthless *bool `json:"ruthless,omitempty"`

	// Sanctified PoE2 only; always true if present
	Sanctified  *bool         `json:"sanctified,omitempty"`
	ScourgeMods *[]string     `json:"scourgeMods,omitempty"`
	Scourged    *ItemScourged `json:"scourged,omitempty"`

	// SeaRaceReward always true if present
	SeaRaceReward *bool `json:"seaRaceReward,omitempty"`

	// Searing always true if present
	Searing      *bool   `json:"searing,omitempty"`
	SecDescrText *string `json:"secDescrText,omitempty"`

	// Shaper always true if present
	Shaper *bool `json:"shaper,omitempty"`
	Socket *int  `json:"socket,omitempty"`

	// SocketedIcon PoE2 only; an image URL to use when this item is in the socket of another item
	SocketedIcon  *string       `json:"socketedIcon,omitempty"`
	SocketedItems *[]Item       `json:"socketedItems,omitempty"`
	Sockets       *[]ItemSocket `json:"sockets,omitempty"`

	// Split always true if present
	Split         *bool   `json:"split,omitempty"`
	StackSize     *int    `json:"stackSize,omitempty"`
	StackSizeText *string `json:"stackSizeText,omitempty"`

	// Support always true if present
	Support *bool `json:"support,omitempty"`

	// SupportGemRequirements PoE2 only
	SupportGemRequirements *[]ItemProperty `json:"supportGemRequirements,omitempty"`

	// Synthesised always true if present
	Synthesised *bool `json:"synthesised,omitempty"`

	// TamedBeastProperties PoE2 only
	TamedBeastProperties *[]ItemProperty `json:"tamedBeastProperties,omitempty"`

	// Tangled always true if present
	Tangled *bool `json:"tangled,omitempty"`

	// ThRaceReward always true if present
	ThRaceReward  *bool               `json:"thRaceReward,omitempty"`
	TypeLine      string              `binding:"required" json:"typeLine"`
	UltimatumMods *[]ItemUltimatumMod `json:"ultimatumMods,omitempty"`

	// UnidentifiedTier PoE2 only
	UnidentifiedTier *int `json:"unidentifiedTier,omitempty"`

	// Unmodifiable always true if present
	Unmodifiable *bool `json:"unmodifiable,omitempty"`

	// UnmodifiableExceptChaos always true if present
	UnmodifiableExceptChaos *bool     `json:"unmodifiableExceptChaos,omitempty"`
	UtilityMods             *[]string `json:"utilityMods,omitempty"`

	// Veiled always true if present
	Veiled *bool `json:"veiled,omitempty"`

	// VeiledMods random video identifier
	VeiledMods *[]string `json:"veiledMods,omitempty"`
	Verified   bool      `binding:"required" json:"verified"`

	// Vestigial PoE1 only; always true if present
	Vestigial *bool `json:"vestigial,omitempty"`
	W         int   `binding:"required" json:"w"`

	// WeaponRequirements PoE2 only
	WeaponRequirements *[]ItemProperty `json:"weaponRequirements,omitempty"`
	X                  *int            `json:"x,omitempty"`
	Y                  *int            `json:"y,omitempty"`
}

// ItemColour PoE1 only; S, D, I, or G
type ItemColour string

// ItemRarity Normal, Magic, Rare, or Unique
type ItemRarity string

// ItemCrucible defines model for ItemCrucible.
type ItemCrucible struct {
	// Layout URL to an image of the tree layout
	Layout string `binding:"required" json:"layout"`

	// Nodes the key is the string value of the node index
	Nodes map[string]CrucibleNode `binding:"required" json:"nodes"`
}

// ItemEnshrouded defines model for ItemEnshrouded.
type ItemEnshrouded struct {
	Progress int     `binding:"required" json:"progress"`
	Total    int     `binding:"required" json:"total"`
	Unique   *string `json:"unique,omitempty"`
}

// ItemExtended defines model for ItemExtended.
type ItemExtended struct {
	Prefixes *int `json:"prefixes,omitempty"`
	Suffixes *int `json:"suffixes,omitempty"`
}

// ItemFilter defines model for ItemFilter.
type ItemFilter struct {
	Description string `binding:"required" json:"description"`

	// Filter not present when listing all filters
	Filter     *string `json:"filter,omitempty"`
	FilterName string  `binding:"required" json:"filter_name"`
	Id         string  `binding:"required" json:"id"`

	// Public always true if present
	Public *bool `json:"public,omitempty"`
	Realm  Realm `binding:"required" json:"realm"`

	// Type either Normal or Ruthless
	Type ItemFilterType `binding:"required" json:"type"`

	// Validation not present when listing all filters
	Validation *ItemFilterValidation `json:"validation,omitempty"`
	Version    string                `binding:"required" json:"version"`
}

// ItemFilterType either Normal or Ruthless
type ItemFilterType string

// ItemFilterValidation defines model for ItemFilterValidation.
type ItemFilterValidation struct {
	Valid bool `binding:"required" json:"valid"`

	// Validated date time (ISO8601)
	Validated *time.Time `json:"validated,omitempty"`

	// Version game version
	Version *string `json:"version,omitempty"`
}

// ItemHybrid defines model for ItemHybrid.
type ItemHybrid struct {
	BaseTypeName string          `binding:"required" json:"baseTypeName"`
	ExplicitMods *[]string       `json:"explicitMods,omitempty"`
	IsVaalGem    *bool           `json:"isVaalGem,omitempty"`
	Properties   *[]ItemProperty `json:"properties,omitempty"`
	SecDescrText *string         `json:"secDescrText,omitempty"`
}

// ItemIncubatedItem defines model for ItemIncubatedItem.
type ItemIncubatedItem struct {
	// Level monster level required to progress
	Level    int    `binding:"required" json:"level"`
	Name     string `binding:"required" json:"name"`
	Progress int    `binding:"required" json:"progress"`
	Total    int    `binding:"required" json:"total"`
}

// ItemJewelData defines model for ItemJewelData.
type ItemJewelData struct {
	Radius       *int    `json:"radius,omitempty"`
	RadiusMin    *int    `json:"radiusMin,omitempty"`
	RadiusVisual *string `json:"radiusVisual,omitempty"`

	// Subgraph only present on cluster jewels
	Subgraph *ItemJewelDataSubgraph `json:"subgraph,omitempty"`
	Type     string                 `binding:"required" json:"type"`
}

// ItemJewelDataSubgraph defines model for ItemJewelDataSubgraph.
type ItemJewelDataSubgraph struct {
	// Groups the key is the string value of the group id
	Groups map[string]PassiveGroup `binding:"required" json:"groups"`

	// Nodes the key is the string value of the node identifier
	Nodes map[string]PassiveNode `binding:"required" json:"nodes"`
}

// ItemLogbookMod defines model for ItemLogbookMod.
type ItemLogbookMod struct {
	Faction Faction `binding:"required" json:"faction"`

	// Name area name
	Name string `binding:"required" json:"name"`
}

// ItemMercenarySkill defines model for ItemMercenarySkill.
type ItemMercenarySkill struct {
	Hash     int        `binding:"required" json:"hash"`
	Icon     string     `binding:"required" json:"icon"`
	Name     string     `binding:"required" json:"name"`
	Supports *[]Support `json:"supports,omitempty"`
}

// ItemMod defines model for ItemMod.
type ItemMod struct {
	Description string        `binding:"required" json:"description"`
	Flags       *ItemModFlags `json:"flags,omitempty"`
}

// ItemModFlags defines model for ItemModFlags.
type ItemModFlags struct {
	// Crafted always true if present
	Crafted *bool `json:"crafted,omitempty"`

	// Desecrated PoE2 only; always true if present
	Desecrated *bool `json:"desecrated,omitempty"`

	// Fractured always true if present
	Fractured *bool `json:"fractured,omitempty"`

	// Mutated always true if present
	Mutated *bool `json:"mutated,omitempty"`

	// Vestigial PoE1 only; always true if present
	Vestigial *bool `json:"vestigial,omitempty"`
}

// ItemProperty defines model for ItemProperty.
type ItemProperty struct {
	DisplayMode *int    `json:"displayMode,omitempty"`
	Icon        *string `json:"icon,omitempty"`
	Name        string  `binding:"required" json:"name"`

	// Progress rounded to 2 decimal places
	Progress *float64            `json:"progress,omitempty"`
	Suffix   *string             `json:"suffix,omitempty"`
	Type     *int                `json:"type,omitempty"`
	Values   []ItemPropertyValue `binding:"required" json:"values"`
}

// ItemPropertyValue defines model for ItemPropertyValue.
type ItemPropertyValue = ItemValue

// ItemReward defines model for ItemReward.
type ItemReward struct {
	Label string `binding:"required" json:"label"`

	// Rewards the key is a string representing the type of reward. The value is the amount
	Rewards map[string]int `binding:"required" json:"rewards"`
}

// ItemScourged defines model for ItemScourged.
type ItemScourged struct {
	// Level monster level required to progress
	Level    *int `json:"level,omitempty"`
	Progress *int `json:"progress,omitempty"`

	// Tier 1-3 for items, 1-10 for maps
	Tier  int  `binding:"required" json:"tier"`
	Total *int `json:"total,omitempty"`
}

// ItemSocket defines model for ItemSocket.
type ItemSocket struct {
	// Attr PoE1 only; S, D, I, G, A, or DV
	Attr  *ItemSocketAttr `json:"attr,omitempty"`
	Group int             `binding:"required" json:"group"`

	// Item PoE2 only; emerald, sapphire, ruby, rune, soulcore, primaltalisman, vividtalisman, wildtalisman, sacredtalisman, activegem, or supportgem
	Item *ItemSocketItem `json:"item,omitempty"`

	// SColour PoE1 only; R, G, B, W, A, or DV
	SColour *ItemSocketSColour `json:"sColour,omitempty"`

	// Type PoE2 only; gem, jewel, or rune
	Type *ItemSocketType `json:"type,omitempty"`
}

// ItemSocketAttr PoE1 only; S, D, I, G, A, or DV
type ItemSocketAttr string

// ItemSocketItem PoE2 only; emerald, sapphire, ruby, rune, soulcore, primaltalisman, vividtalisman, wildtalisman, sacredtalisman, activegem, or supportgem
type ItemSocketItem string

// ItemSocketSColour PoE1 only; R, G, B, W, A, or DV
type ItemSocketSColour string

// ItemSocketType PoE2 only; gem, jewel, or rune
type ItemSocketType string

// ItemUltimatumMod defines model for ItemUltimatumMod.
type ItemUltimatumMod struct {
	Tier int `binding:"required" json:"tier"`

	// Type text used to display ultimatum icons
	Type string `binding:"required" json:"type"`
}

// Ladder defines model for Ladder.
type Ladder struct {
	// CachedSince date time (ISO8601)
	CachedSince *time.Time    `json:"cached_since,omitempty"`
	Entries     []LadderEntry `binding:"required" json:"entries"`
	Total       int           `binding:"required" json:"total"`
}

// Ladder2 defines model for Ladder2.
type Ladder2 struct {
	Entries []EventLadderEntry `binding:"required" json:"entries"`
	Total   int                `binding:"required" json:"total"`
}

// Ladder3 defines model for Ladder3.
type Ladder3 struct {
	Entries []PvPLadderTeamEntry `binding:"required" json:"entries"`
	Total   int                  `binding:"required" json:"total"`
}

// LadderEntry defines model for LadderEntry.
type LadderEntry struct {
	Account    *Account             `json:"account,omitempty"`
	Character  LadderEntryCharacter `binding:"required" json:"character"`
	Dead       *bool                `json:"dead,omitempty"`
	Ineligible *bool                `json:"ineligible,omitempty"`
	Public     *bool                `json:"public,omitempty"`
	Rank       int                  `binding:"required" json:"rank"`
	Retired    *bool                `json:"retired,omitempty"`
}

// LadderEntryCharacter defines model for LadderEntryCharacter.
type LadderEntryCharacter struct {
	Class string `binding:"required" json:"class"`

	// Depth deepest Delve depth completed
	Depth      *Depth `json:"depth,omitempty"`
	Experience *int   `json:"experience,omitempty"`

	// Id a unique 64 digit hexadecimal string
	Id    string `binding:"required" json:"id"`
	Level int    `binding:"required" json:"level"`
	Name  string `binding:"required" json:"name"`

	// Progress the values of this depend on the league objective
	Progress *map[string]interface{} `json:"progress,omitempty"`

	// Score count of league objective completions
	Score *int `json:"score,omitempty"`

	// Time time taken to complete the league objective in seconds
	Time *int `json:"time,omitempty"`
}

// League defines model for League.
type League struct {
	// AncestorEvent always true if present
	AncestorEvent *bool           `json:"ancestorEvent,omitempty"`
	Category      *LeagueCategory `json:"category,omitempty"`

	// DelveEvent always true if present
	DelveEvent  *bool   `json:"delveEvent,omitempty"`
	Description *string `json:"description,omitempty"`

	// EndAt date time (ISO8601)
	EndAt *time.Time `json:"endAt,omitempty"`

	// Event always true if present
	Event *bool   `json:"event,omitempty"`
	Goal  *string `json:"goal,omitempty"`
	Id    string  `binding:"required" json:"id"`

	// LeagueEvent always true if present
	LeagueEvent *bool `json:"leagueEvent,omitempty"`

	// Name the league's name
	Name *string `json:"name,omitempty"`

	// Realm pc, xbox, or sony
	Realm *Realm `json:"realm,omitempty"`

	// RegisterAt date time (ISO8601)
	RegisterAt *time.Time    `json:"registerAt,omitempty"`
	Rules      *[]LeagueRule `json:"rules,omitempty"`

	// ScoreEvent always true if present
	ScoreEvent *bool `json:"scoreEvent,omitempty"`

	// StartAt date time (ISO8601)
	StartAt *time.Time `json:"startAt,omitempty"`

	// TimedEvent always true if present
	TimedEvent *bool `json:"timedEvent,omitempty"`

	// Url a url link to a Path of Exile forum thread
	Url *string `json:"url,omitempty"`
}

// LeagueAccount defines model for LeagueAccount.
type LeagueAccount struct {
	AtlasPassiveTrees []LeagueAccountAtlasPassiveTree `binding:"required" json:"atlas_passive_trees"`
	AtlasPassives     *LeagueAccountAtlasPassives     `json:"atlas_passives,omitempty"`
}

// LeagueAccountAtlasPassiveTree defines model for LeagueAccountAtlasPassiveTree.
type LeagueAccountAtlasPassiveTree struct {
	Hashes []int  `binding:"required" json:"hashes"`
	Name   string `binding:"required" json:"name"`
}

// LeagueAccountAtlasPassives defines model for LeagueAccountAtlasPassives.
type LeagueAccountAtlasPassives struct {
	Hashes []int `binding:"required" json:"hashes"`
}

// LeagueCategory defines model for LeagueCategory.
type LeagueCategory struct {
	// Current set for the active challenge leagues; always true if present
	Current *bool `json:"current,omitempty"`

	// Id the league category, e.g. Affliction
	Id string `binding:"required" json:"id"`
}

// LeagueRule defines model for LeagueRule.
type LeagueRule struct {
	Description *string `json:"description,omitempty"`

	// Id examples: Hardcore, NoParties (SSF)
	Id   LeagueRuleId `binding:"required" json:"id"`
	Name string       `binding:"required" json:"name"`
}

// LeagueRuleId examples: Hardcore, NoParties (SSF)
type LeagueRuleId string

// ListCharactersResponse defines model for ListCharactersResponse.
type ListCharactersResponse struct {
	Characters []Character `binding:"required" json:"characters"`
}

// ListLeaguesResponse defines model for ListLeaguesResponse.
type ListLeaguesResponse struct {
	Leagues []League `binding:"required" json:"leagues"`
}

// ListPvpMatchesResponse defines model for ListPvpMatchesResponse.
type ListPvpMatchesResponse struct {
	Matches []PvPMatch `binding:"required" json:"matches"`
}

// ListStashesResponse defines model for ListStashesResponse.
type ListStashesResponse struct {
	Stashes []StashTab `binding:"required" json:"stashes"`
}

// Market defines model for Market.
type Market struct {
	HighestRatio map[string]int `binding:"required" json:"highest_ratio"`
	HighestStock map[string]int `binding:"required" json:"highest_stock"`
	League       string         `binding:"required" json:"league"`
	LowestRatio  map[string]int `binding:"required" json:"lowest_ratio"`
	LowestStock  map[string]int `binding:"required" json:"lowest_stock"`

	// MarketId base item ids separated by a pipe. Example: Metadata/Items/Currency/CurrencyRerollRare|Metadata/Items/Currency/CurrencyModValues
	MarketId MarketMarketId `binding:"required" json:"market_id"`

	// MarketPair base item ids
	MarketPair []string `binding:"required" json:"market_pair"`

	// VolumeTraded the keys are the market currencies. Example: Metadata/Items/Currency/CurrencyRerollRare
	VolumeTraded map[string]int `binding:"required" json:"volume_traded"`
}

// MarketMarketId base item ids separated by a pipe. Example: Metadata/Items/Currency/CurrencyRerollRare|Metadata/Items/Currency/CurrencyModValues
type MarketMarketId string

// PassiveGroup defines model for PassiveGroup.
type PassiveGroup struct {
	// IsProxy always true if present
	IsProxy *bool `json:"isProxy,omitempty"`

	// Nodes the node identifiers associated with this group
	Nodes  []string `binding:"required" json:"nodes"`
	Orbits []int    `binding:"required" json:"orbits"`

	// Proxy identifier of the placeholder node
	Proxy *string `json:"proxy,omitempty"`
	X     float32 `binding:"required" json:"x"`
	Y     float32 `binding:"required" json:"y"`
}

// PassiveNode defines model for PassiveNode.
type PassiveNode struct {
	// ActiveEffectImage active mastery or tattoo background image
	ActiveEffectImage *string `json:"activeEffectImage,omitempty"`

	// ActiveIcon active mastery image
	ActiveIcon      *string `json:"activeIcon,omitempty"`
	AscendancyName  *string `json:"ascendancyName,omitempty"`
	ClassStartIndex *int    `json:"classStartIndex,omitempty"`

	// ExpansionJewel cluster jewel information
	ExpansionJewel *PassiveNodeExpansionJewel `json:"expansionJewel,omitempty"`
	FlavourText    *[]string                  `json:"flavourText,omitempty"`

	// GrantedDexterity sum of stats on this node that grant dexterity
	GrantedDexterity *int `json:"grantedDexterity,omitempty"`

	// GrantedIntelligence sum of stats on this node that grant intelligence
	GrantedIntelligence  *int `json:"grantedIntelligence,omitempty"`
	GrantedPassivePoints *int `json:"grantedPassivePoints,omitempty"`

	// GrantedStrength sum of stats on this node that grant strength
	GrantedStrength *int `json:"grantedStrength,omitempty"`

	// Group the key value to look up in the groups table
	Group *string `json:"group,omitempty"`
	Icon  *string `json:"icon,omitempty"`

	// In node identifiers of nodes connected to this one
	In []string `binding:"required" json:"in"`

	// InactiveIcon inactive mastery image
	InactiveIcon *string `json:"inactiveIcon,omitempty"`

	// IsAscendancyStart always true if present
	IsAscendancyStart *bool `json:"isAscendancyStart,omitempty"`

	// IsBlighted always true if present
	IsBlighted *bool `json:"isBlighted,omitempty"`

	// IsJewelSocket always true if present
	IsJewelSocket *bool `json:"isJewelSocket,omitempty"`

	// IsKeystone always true if present
	IsKeystone *bool `json:"isKeystone,omitempty"`

	// IsMastery always true if present
	IsMastery *bool `json:"isMastery,omitempty"`

	// IsMultipleChoice always true if present
	IsMultipleChoice *bool `json:"isMultipleChoice,omitempty"`

	// IsMultipleChoiceOption always true if present
	IsMultipleChoiceOption *bool `json:"isMultipleChoiceOption,omitempty"`

	// IsNotable always true if present
	IsNotable *bool `json:"isNotable,omitempty"`

	// IsProxy always true if present
	IsProxy *bool `json:"isProxy,omitempty"`

	// IsTattoo always true if present
	IsTattoo       *bool                       `json:"isTattoo,omitempty"`
	MasteryEffects *[]PassiveNodeMasteryEffect `json:"masteryEffects,omitempty"`
	Name           *string                     `json:"name,omitempty"`

	// Orbit the orbit this node occupies within it's group
	Orbit *int `json:"orbit,omitempty"`

	// OrbitIndex the index of this node in the group's orbit
	OrbitIndex *int `json:"orbitIndex,omitempty"`

	// Out node identifiers of nodes this one connects to
	Out []string `binding:"required" json:"out"`

	// Recipe components required for Blight crafting this node.
	//             each string is one of ClearOil, SepiaOil, AmberOil, VerdantOil,
	// TealOil, AzureOil, IndigoOil, VioletOil, CrimsonOil,
	// BlackOil, OpalescentOil, SilverOil, GoldenOil, or PrismaticOil
	Recipe       *[]string `json:"recipe,omitempty"`
	ReminderText *[]string `json:"reminderText,omitempty"`

	// Skill skill hash
	Skill *string `json:"skill,omitempty"`

	// Stats stat descriptions
	Stats *[]string `json:"stats,omitempty"`
}

// PassiveNodeExpansionJewel defines model for PassiveNodeExpansionJewel.
type PassiveNodeExpansionJewel struct {
	Index *int `json:"index,omitempty"`

	// Parent the parent node identifier
	Parent *string `json:"parent,omitempty"`

	// Proxy the proxy node identifier
	Proxy *string `json:"proxy,omitempty"`
	Size  *int    `json:"size,omitempty"`
}

// PassiveNodeMasteryEffect defines model for PassiveNodeMasteryEffect.
type PassiveNodeMasteryEffect struct {
	// Effect effect hash
	Effect       int       `binding:"required" json:"effect"`
	ReminderText *[]string `json:"reminderText,omitempty"`

	// Stats stat descriptions
	Stats []string `binding:"required" json:"stats"`
}

// PublicStashChange defines model for PublicStashChange.
type PublicStashChange struct {
	AccountName *string `json:"accountName,omitempty"`

	// Id a unique 64 digit hexadecimal string
	Id    string `binding:"required" json:"id"`
	Items []Item `binding:"required" json:"items"`

	// League the league's name
	League *string `json:"league,omitempty"`

	// Public if false then optional properties will be null
	Public bool `binding:"required" json:"public"`

	// Stash the name of the stash
	Stash     *string `json:"stash,omitempty"`
	StashType string  `binding:"required" json:"stashType"`
}

// PvPLadderTeamEntry defines model for PvPLadderTeamEntry.
type PvPLadderTeamEntry struct {
	CumulativeOpponentPoints *int `json:"cumulative_opponent_points,omitempty"`
	GamesPlayed              *int `json:"games_played,omitempty"`

	// LastGameTime date time (ISO8601)
	LastGameTime *time.Time            `json:"last_game_time,omitempty"`
	Members      []PvPLadderTeamMember `binding:"required" json:"members"`
	Points       *int                  `json:"points,omitempty"`
	Rank         int                   `binding:"required" json:"rank"`

	// Rating only present if the PvP Match uses Glicko ratings
	Rating *int `json:"rating,omitempty"`
}

// PvPLadderTeamMember defines model for PvPLadderTeamMember.
type PvPLadderTeamMember struct {
	Account   Account                      `binding:"required" json:"account"`
	Character PvPLadderTeamMemberCharacter `binding:"required" json:"character"`

	// Public always true if present
	Public *bool `json:"public,omitempty"`
}

// PvPLadderTeamMemberCharacter defines model for PvPLadderTeamMemberCharacter.
type PvPLadderTeamMemberCharacter struct {
	Class string `binding:"required" json:"class"`

	// Id a unique 64 digit hexadecimal string
	Id     string  `binding:"required" json:"id"`
	League *string `json:"league,omitempty"`
	Level  int     `binding:"required" json:"level"`
	Name   string  `binding:"required" json:"name"`

	// Score count of league objective completions
	Score *int `json:"score,omitempty"`
}

// PvPMatch defines model for PvPMatch.
type PvPMatch struct {
	// Complete always true if present
	Complete    *bool  `json:"complete,omitempty"`
	Description string `binding:"required" json:"description"`

	// EndAt date time (ISO8601)
	EndAt         *time.Time `json:"endAt,omitempty"`
	GlickoRatings bool       `binding:"required" json:"glickoRatings"`

	// Id the match's name
	Id string `binding:"required" json:"id"`

	// InProgress always true if present
	InProgress *bool `json:"inProgress,omitempty"`

	// Pvp always true
	Pvp bool `binding:"required" json:"pvp"`

	// Realm pc, xbox, or sony
	Realm *Realm `json:"realm,omitempty"`

	// RegisterAt date time (ISO8601)
	RegisterAt *time.Time `json:"registerAt,omitempty"`

	// StartAt date time (ISO8601)
	StartAt *time.Time `json:"startAt,omitempty"`

	// Style Blitz, Swiss, or Arena
	Style PvPMatchStyle `binding:"required" json:"style"`

	// Upcoming always true if present
	Upcoming *bool `json:"upcoming,omitempty"`

	// Url a url link to a Path of Exile forum thread
	Url *string `json:"url,omitempty"`
}

// PvPMatchStyle Blitz, Swiss, or Arena
type PvPMatchStyle string

// Realm defines model for Realm.
type Realm string

// StashTab defines model for StashTab.
type StashTab struct {
	Children *[]StashTab `json:"children,omitempty"`

	// Folder a 10 digit hexadecimal string
	Folder *string `json:"folder,omitempty"`

	// Id a 10 digit hexadecimal string
	Id       string           `binding:"required" json:"id"`
	Index    *int             `json:"index,omitempty"`
	Items    *[]Item          `json:"items,omitempty"`
	Metadata StashTabMetadata `binding:"required" json:"metadata"`
	Name     string           `binding:"required" json:"name"`

	// Parent a 10 digit hexadecimal string
	Parent *string `json:"parent,omitempty"`
	Type   string  `binding:"required" json:"type"`
}

// StashTabMetadata defines model for StashTabMetadata.
type StashTabMetadata struct {
	// Colour 6 digit hex colour
	Colour *string `json:"colour,omitempty"`

	// Folder always true if present
	Folder *bool `json:"folder,omitempty"`

	// Map various game specific properties
	Map *map[string]interface{} `json:"map,omitempty"`

	// Public always true if present
	Public *bool `json:"public,omitempty"`
}

// Stream defines model for Stream.
type Stream struct {
	Image  string `binding:"required" json:"image"`
	Name   string `binding:"required" json:"name"`
	Status string `binding:"required" json:"status"`
}

// Support defines model for Support.
type Support struct {
	Hash int    `binding:"required" json:"hash"`
	Name string `binding:"required" json:"name"`
	Tier int    `binding:"required" json:"tier"`
}

// Twitch defines model for Twitch.
type Twitch struct {
	Name string `binding:"required" json:"name"`
}

// UpdateItemFilterRequest defines model for UpdateItemFilterRequest.
type UpdateItemFilterRequest struct {
	Description *string `json:"description,omitempty"`
	Filter      *string `json:"filter,omitempty"`
	FilterName  *string `json:"filter_name,omitempty"`

	// Public must be true if present
	Public *bool `json:"public,omitempty"`

	// Realm pc, xbox, sony, or poe2
	Realm *Realm `json:"realm,omitempty"`

	// Type either Normal or Ruthless
	Type    *UpdateItemFilterRequestType `json:"type,omitempty"`
	Version *string                      `json:"version,omitempty"`
}

// UpdateItemFilterRequestType either Normal or Ruthless
type UpdateItemFilterRequestType string

// UpdateItemFilterResponse defines model for UpdateItemFilterResponse.
type UpdateItemFilterResponse struct {
	// Error an "Accepted" error object
	Error  *Error     `json:"error,omitempty"`
	Filter ItemFilter `binding:"required" json:"filter"`
}

// CreateItemFilterParams defines parameters for CreateItemFilter.
type CreateItemFilterParams struct {
	// Validate set to true to validate the filter against the current game version
	Validate *string `form:"validate,omitempty" json:"validate,omitempty"`
}

// UpdateItemFilterParams defines parameters for UpdateItemFilter.
type UpdateItemFilterParams struct {
	// Validate set to true to validate the filter against the current game version
	Validate *string `form:"validate,omitempty" json:"validate,omitempty"`
}

// ListLeaguesParams defines parameters for ListLeagues.
type ListLeaguesParams struct {
	// Type type can be one of the following: main retrieves permanent and current challenge leagues (default)
	// event retrieves current event leagues
	// season (PoE1 only) retrieves leagues in a particular season. Use season to set the season to query
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// Limit restricts the amount of results returned. Maximum is 50 (default)
	Limit *string `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset can be used with limit above to scroll through the list
	Offset *string `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetLeagueEventLadderParams defines parameters for GetLeagueEventLadder.
type GetLeagueEventLadderParams struct {
	// Limit restricts the amount of results returned. Default is 20. Maximum is 500
	Limit *string `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset can be used with limit above to scroll through the list
	Offset *string `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetLeagueLadderParams defines parameters for GetLeagueLadder.
type GetLeagueLadderParams struct {
	// Sort sort (PoE1 only) can be one of the following: xp sorts the ladder by experience
	// depth sorts the ladder by Delve depth
	// depthsolo sorts the ladder by Delve (Solo) depth
	// ancestor sorts the ladder by Ancestor rank
	// time sorts the ladder by objective finish time
	// score sorts the ladder by objective score
	//
	// class returns characters of a specific class sorted by experience. Use class to set the class. Options are:
	//
	// scion
	// marauder
	// ranger
	// witch
	// duelist
	// templar
	// shadow  The default sort type will either be xp or time depending on the league.
	Sort *string `form:"sort,omitempty" json:"sort,omitempty"`

	// Limit restricts the amount of results returned. Default is 20. Maximum is 500
	Limit *string `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset can be used with limit above to scroll through the list
	Offset *string `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetPublicStashesParams defines parameters for GetPublicStashes.
type GetPublicStashesParams struct {
	// Id is a pagination code received from this endpoint
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// ListPvpMatchesParams defines parameters for ListPvpMatches.
type ListPvpMatchesParams struct {
	// Type type can be one of the following: upcoming retrieves upcoming matches (default)
	// season retrieves matches in a particular season. Use season to set the season to query
	// league retrieves matches in a particular league. Use league to set the league to query
	Type *string `form:"type,omitempty" json:"type,omitempty"`
}

// GetPvpMatchLadderParams defines parameters for GetPvpMatchLadder.
type GetPvpMatchLadderParams struct {
	// Limit restricts the amount of results returned. Default is 20. Maximum is 200
	Limit *string `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset can be used with limit above to scroll through the list
	Offset *string `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateItemFilterJSONRequestBody defines body for CreateItemFilter for application/json ContentType.
type CreateItemFilterJSONRequestBody = CreateItemFilterRequest

// UpdateItemFilterJSONRequestBody defines body for UpdateItemFilter for application/json ContentType.
type UpdateItemFilterJSONRequestBody = UpdateItemFilterRequest
